### PR TITLE
Rename project to Dyph

### PR DESCRIPTION
**Pull request by jelder**
This removes the 3 from the project name as discussed. Impetus for doing this now: running `bundle` in other gems which depend on this print a scary warning about mixing sources, due to our current use of GemFury. We'd rather just publish this on the public RubyGems. The license is already MIT and this repository is already public.

If we all agree, after merging, I will rename the repository and ship a new public gem.

### CODE REVIEW

**Comment by jelder** [comment]
CodeClimate is complaining about a pre-existing issue because the file name changed.

**Comment by aamontal** [comment]
@jelder feel free to vet the docs, maybe add an explanation of Min Diff feature too

**Comment by jelder** [comment]
@aamontal `min_diff` is in a branch off of this one. But I will update the README over there.

**Comment by jelder** [comment]
@kevinmook Cool?

**Comment by kevinmook** [comment]
👍

**Pull request merged**
